### ISSUE TITLE
关于JBChat

### ISSUE THREAD

**Issue by Runeston** [nicktimebreak/xteko#4]
您好，您的JBChat很好看很实用，但我在使用过程中是优先复制读取剪贴板，而不是读取选中，因此需要收到点击切换，能否默认显示剪贴板模式，或者教我更改默认模式，谢谢

**Comment by Nicked639** [comment]
> 您好，您的JBChat很好看很实用，但我在使用过程中是优先复制读取剪贴板，而不是读取选中，因此需要收到点击切换，能否默认显示剪贴板模式，或者教我更改默认模式，谢谢

最新版本的已经支持不同模式写入 cache 了，可以满足你的需求，更新就好。
