### ISSUE TITLE
Javbus.com 昨天更新后强制要求登录

### ISSUE THREAD

**Issue by QYQSDTC** [nicktimebreak/xteko#6]
昨天 javbus.com 更新了后强制要求登录，然后脚本就上不去了，大佬能不能更新一下

**Comment by Nicked639** [comment]
> 昨天 javbus.com 更新了后强制要求登录，然后脚本就上不去了，大佬能不能更新一下

用网页访问的确会跳转到登陆页面，但是在JSBox脚本里还是能请求到数据正常显示。
太久没更新了，已经看不懂自己写的东西了😬
